import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const api=async(path,options={},token='')=>{let r=await fetch(path,{...options,headers:{...options.headers,...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Request failed'}))).detail);return r};
function App(){const[token,setToken]=useState(localStorage.token||'');const[mode,setMode]=useState('login');const[account,setAccount]=useState();const[file,setFile]=useState();const[format,setFormat]=useState('webp');const[message,setMessage]=useState('');
const load=()=>api('/api/me',{},token).then(r=>r.json()).then(setAccount).catch(()=>{localStorage.removeItem('token');setToken('')});useEffect(()=>{if(token)load()},[token]);
const auth=async e=>{e.preventDefault();let d=new FormData(e.currentTarget);try{let r=await api('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:d.get('email'),password:d.get('password')})});let{token:t}=await r.json();localStorage.token=t;setToken(t)}catch(e){setMessage(e.message)}};
const convert=async()=>{if(!file)return setMessage('Choose an image first.');setMessage('Converting…');let d=new FormData();d.append('image',file);try{let r=await api('/api/convert?destination='+format,{method:'POST',body:d},token),blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='converted.'+format;a.click();URL.revokeObjectURL(a.href);setMessage(`Done — used ${r.headers.get('X-Usage-Source')} allowance.`);load()}catch(e){setMessage(e.message)}};
const pay=async kind=>{try{let r=await api('/api/billing/checkout/'+kind,{method:'POST'},token);location.href=(await r.json()).checkoutUrl}catch(e){setMessage(e.message)}};
if(!token)return <main className="auth"><h1>PixelShift</h1><p>Private image conversion. Your files are never stored.</p><form onSubmit={auth}><input name="email" placeholder="Email" type="email" required/><input name="password" placeholder="Password (8+ characters)" type="password" minLength="8" required/><button>{mode==='login'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already have an account? Sign in'}</button><small>{message}</small></main>;
return <main><header><h1>PixelShift</h1><div>{account?.email} <button className="link" onClick={()=>{localStorage.removeItem('token');setToken('')}}>Sign out</button></div></header><section className="hero"><h2>Convert an image, then it disappears.</h2><p>We process files in memory and never store uploads or converted images.</p><input type="file" accept="image/*,.heic,.heif" onChange={e=>setFile(e.target.files[0])}/><select value={format} onChange={e=>setFormat(e.target.value)}>{['jpeg','png','webp','gif','bmp','tiff','pdf'].map(x=><option key={x}>{x.toUpperCase()}</option>)}</select><button onClick={convert}>Convert & download</button><small>{message}</small></section><section className="cards"><article><h3>Free</h3><b>{account?.freeRemaining ?? 0} / 3</b><p>free conversions remaining today</p></article><article><h3>Credit wallet</h3><b>{account?.creditBalance ?? 0}</b><p>$0.01 per conversion</p><button onClick={()=>pay('credits')}>Buy 100 credits — $1</button></article><article className="pro"><h3>Pro</h3><b>{account?.pro?'Active':'$0.30 / month'}</b><p>Fair-use conversions, no daily limit.</p><button onClick={()=>pay('pro')}>{account?.pro?'Pro active':'Upgrade to Pro'}</button></article></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
